---
- name: Install sysvinit Tomcat Service
  tags: tomcat
  notify: service restart {{ tomcat_service_name }}
  template:
    src=tomcat_server_sysvinit_template
    dest=/etc/init.d/{{ tomcat_service_name }}
    owner=0
    group=0
    mode=0755
