---
- name: Install upstart Tomcat Service
  tags: tomcat
  become: yes
  notify: service restart {{ tomcat_service_name }}
  template:
    src={{ tomcat_server_upstart_template }}
    dest=/etc/init/{{ tomcat_service_name }}.conf
    owner=0
    group=0
    mode=0644
